name: Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (Debug)
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select latest Xcode
        run: |
          XCODE_PATH=$(ls -d /Applications/Xcode*.app 2>/dev/null | sort -V | tail -1)
          echo "Using Xcode at: $XCODE_PATH"
          sudo xcode-select -s "$XCODE_PATH/Contents/Developer"
          xcodebuild -version

      - name: Build
        run: |
          xcodebuild build \
            -project lsom.xcodeproj \
            -scheme lsom \
            -configuration Debug \
            -destination 'platform=macOS' \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty --color || exit ${PIPESTATUS[0]}

      - name: Report result
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Build succeeded"
          else
            echo "❌ Build failed"
            exit 1
          fi
