name: Test

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select latest Xcode
        run: |
          XCODE_PATH=$(ls -d /Applications/Xcode*.app 2>/dev/null | sort -V | tail -1)
          echo "Using Xcode at: $XCODE_PATH"
          sudo xcode-select -s "$XCODE_PATH/Contents/Developer"
          xcodebuild -version

      - name: Run tests
        run: |
          xcodebuild test \
            -project lsom.xcodeproj \
            -scheme lsom \
            -destination 'platform=macOS' \
            -resultBundlePath TestResults.xcresult \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty --color --report junit --output test-results.xml || exit ${PIPESTATUS[0]}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            TestResults.xcresult
            test-results.xml
          retention-days: 14

      - name: Report result
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ All tests passed"
          else
            echo "❌ Tests failed — check artifacts for details"
            exit 1
          fi
